[package]
name = "fishfight"
version = "0.3.0"
description = "A tactical 2D shooter"
authors = ["Fish Fight Contributors"]
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = []

[workspace]
members = ["core"]

[profile.dev.package."*"]
opt-level = 3

[dependencies]
core = { path = "./core", package = "fishfight-core", features = ["serde", "serde_json"] }
# ultimate = { path = "../FishFight-ultimate", package = "fishfight-ultimate", optional = true }
ff-particles = { version = "0.1", features = ["serde"] }
macroquad = { version = "0.3.10" }
macroquad-platformer = "0.1"
hecs = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fishsticks = { version = "0.2.0", features = ["bundled-sdl2"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
fishsticks = { version = "0.2.0", default-features = false, features = ["gilrs"] }
